version: '3.3'

services:
  master:
    image: red-sent-m:latest
    build:
      context: ./master
    networks:
      - redis-nwk
    command: bash -c "redis-server /data/redis.conf && redis-sentinel /data/sentinel.conf"
      -


  slave:
    image: red-sent-s:latest
    build:
      context: ./slave
    networks:
      - redis-nwk
    command: bash -c "redis-server /data/redis.conf && redis-sentinel /data/sentinel.conf"

networks:
  redis-nwk:
    driver: bridge